resolver: lts-16.14 # ghc-8.8.4

ghc-options:
  # try and speed up recompilation on the CI server
  "$everything": -O0 -j

# Packages MUST go at the end, since we append to it during the CI.hs script
packages:
- .
