# Use the same resolver as GHC/Hadrian to increase caching
resolver: lts-12.10

ghc-options:
  # try and speed up recompilation on the CI server
  "$everything": -O0 -j

# Packages MUST go at the end, since we append to it during the CI.hs script
packages:
- .
