name: ghc-lib-ghc-9.8.4-ghc-9.6.7
on:
  push:
  pull_request:
jobs:
  runhaskell:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: 9.6.7
          cabal-version: 'latest'
      - name: Install build tools (macOS)
        run: brew install automake
        if: matrix.os == 'macos'
      - name: Configure msys2 (windows)
        shell: bash
        run: |-
          echo "MSYSTEM=CLANG64" >> $GITHUB_ENV
          echo "/c/mingw64/usr/bin" >> $GITHUB_PATH
          echo "/c/msys64/usr/bin" >> $GITHUB_PATH
        if: matrix.os == 'windows'
      - name: Run CI.hs (windows)
        shell: C:\msys64\usr\bin\bash.exe --noprofile --norc -e -o pipefail '{0}'
        run: |-
          pacman -S autoconf automake-wrapper make patch python tar mintty --noconfirm
          cabal run exe:ghc-lib-build-tool --constraint='ghc-lib-gen +semaphore-compat' -- --ghc-flavor ghc-9.8.4
        if: matrix.os == 'windows'
      - name: Run CI.hs (unix)
        shell: bash
        run: cabal run exe:ghc-lib-build-tool --constraint='ghc-lib-gen +semaphore-compat' -- --ghc-flavor ghc-9.8.4
        if: matrix.os == 'ubuntu' || matrix.os ==  'macos'
