name: ghc-lib-runhaskell-ghc-9.10.1
on:
  push:
jobs:
  ghc-9-10:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
    steps:
      - uses: actions/checkout@v2
      - run: |-
          curl -sSL https://get.haskellstack.org/ | sh -s - -f
          curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_GHC_VERSION=9.10.1 BOOTSTRAP_HASKELL_CABAL_VERSION=latest BOOTSTRAP_HASKELL_INSTALL_NO_STACK=1 BOOTSTRAP_HASKELL_INSTALL_NO_STACK_HOOK=1 BOOTSTRAP_HASKELL_ADJUST_BASHRC=P sh
        shell: bash
      - name: Configure PATH (unix)
        run: |-
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/.cabal/bin" >> $GITHUB_PATH
          echo "$HOME/.ghcup/bin" >> $GITHUB_PATH
          echo "$HOME/.ghcup/ghc/9.10.1/bin" >> $GITHUB_PATH
        shell: bash
        if: matrix.os == 'ubuntu' || matrix.os == 'macos'
      - name: Configure PATH (windows)
        run: |-
          echo "C:\\Users\\runneradmin\\AppData\\Roaming\\local\\bin" >> $GITHUB_PATH
          echo "C:\\Users\\runneradmin\\AppData\\Roaming\\cabal\\bin" >> $GITHUB_PATH
          echo "C:\\ghcup\\bin" >> $GITHUB_PATH
          echo "C:\\ghcup\\ghc\\9.10.1\\bin" >> $GITHUB_PATH
        shell: bash
        if: matrix.os == 'windows'
      - name: Print diagnostics
        shell: bash
        run: |-
          echo "wich stack: $(which stack)"
          echo "stack-version: $(stack --version)"
          echo "wich ghc: $(which ghc)"
          echo "ghc-version: $(ghc --version)"
          echo "wich cabal: $(which cabal)"
          echo "cabal: $(cabal --version)"
      - name: Install build tools
        run: brew install automake
        if: matrix.os == 'macos'
      - name: Configure
        shell: bash
        # e.g. Don't recursively delete '.stack-work' (`stack clean --full`)
        run: echo "GHCLIB_AZURE='1'" >> $GITHUB_ENV
      - name: Run CI.hs
        shell: bash
        run: stack runhaskell --stack-yaml stack-exact.yaml --resolver ghc-9.10.1 --package extra --package optparse-applicative CI.hs -- --stack-yaml stack-exact.yaml --resolver ghc-9.10.1 --ghc-flavor "ghc-9.10.1"
